Calculator UI PR
Aseadd/Math-Magicians pull request #2
Opened 2022-09-06 20:36 UTC by Aseadd

## **Hello, Good reviewer**

### Commits made so far
- [ ] Add Calculator.js file
- [ ] Add style for the calculator
- [ ] Add Header and Footer for the page

<img src="https://media4.giphy.com/media/Vbtc9VG51NtzT1Qnv1/giphy.gif"/>

2022-09-06 21:55 UTC, codecaiine requested changes
Hi @Aseadd , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good project implementation :heavy_check_mark: 
- Descriptive PR :heavy_check_mark: 

## Required Changes ♻️


- [ ] **I would like to recommend you to delete all the boilerplate that got created by the CRA (texts, images, and styles)** for example [App.test.js](https://github.com/Aseadd/math-magicians/blob/feature/component/src/App.test.js), [setupTests.js](https://github.com/Aseadd/math-magicians/blob/feature/component/src/setupTests.js), [logo192.png](https://github.com/Aseadd/math-magicians/blob/feature/component/public/logo192.png) . Please delete them :+1: 
- [ ] **Most of information you have in your readme is about capstone project . Please update your readme with this current project informations and details to make it more professional and up to date :+1:** 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-06 21:55 UTC, codecaiine commented on src/App.js
> +// eslint-disable-next-line react/prefer-stateless-function
- [ ] I noticed that you disable a lot **Eslint** . Please remove the **eslint disable** statement and try to fix all the errors you are getting. Because ` Eslint` helps developers to write clean JavaScript codes and adapt best practices when writing the code.  :+1:

2022-09-06 21:55 UTC, codecaiine commented on src/components/calculator.js
> +// eslint-disable-next-line react/prefer-stateless-function
- [ ] I noticed that you disable a lot **Eslint** . Please remove the **eslint disable** statement and try to fix all the errors you are getting. Because ` Eslint` helps developers to write clean JavaScript codes and adapt best practices when writing the code.  :+1:

2022-09-06 21:55 UTC, codecaiine commented on src/components/footer.js
> +// eslint-disable-next-line react/prefer-stateless-function
- [ ] I noticed that you disable a lot **Eslint** . Please remove the **eslint disable** statement and try to fix all the errors you are getting. Because ` Eslint` helps developers to write clean JavaScript codes and adapt best practices when writing the code.  :+1:

2022-09-06 21:55 UTC, codecaiine commented on src/components/calculator.js
> +export default Calculator;
- [ ] Good job so far with your design very impressive :clap: But note that is very important to make your project design color , size , information match with the the guiven design. Please sure that the `Calculator.js` component should match following given design :arrow_down: 

<img width="558" alt="calculator (1)" src="https://user-images.githubusercontent.com/6615394/188747737-8b85afd3-29d1-4539-bb96-1fbe01301e73.png">

#### Your design 

![Screenshot from 2022-09-06 21-36-59](https://user-images.githubusercontent.com/6615394/188747781-f086dcfd-1b31-4f3e-a15d-b12883fba801.png)

2022-09-06 23:36 UTC, Aseadd commented on src/App.js
> +// eslint-disable-next-line react/prefer-stateless-function
ESlint expects component to be written as a pure function react/prefer-stateless-function. But the requirement of the project is to create **class components**. I don't have any way to pass ESLint with class components

2022-09-07 00:14 UTC, Aseadd commented on src/components/calculator.js
> +export default Calculator;
Resolved by making my design look like the given wireframe

2022-09-07 00:24 UTC, brytebee approved these changes
Hi, @Aseadd 👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Implemented suggestions of the previous reviewer.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 09:33 UTC, merged